import json, math, statistics
from datetime import datetime
from pathlib import Path
from typing import List, Dict

class PaperGenerator:
    def __init__(self, config=None):
        self.config = config or {}
        self.title_prefix = self.config.get("title_prefix", "AutoResearch: Automated")
        self.include_ablation = self.config.get("include_ablation", True)
        self.include_analysis = self.config.get("include_analysis", True)

    def generate_paper(self, experiment_records, convergence_data, program_config=None):
        if not experiment_records: return self._empty_paper()
        direction = (program_config or {}).get("direction", "lower")
        finite = [r for r in experiment_records if math.isfinite(r.get("metric_value", 0))]
        pool = finite if finite else experiment_records
        if direction == "lower":
            best = min(pool, key=lambda r: r.get("metric_value", 0))
        else:
            best = max(pool, key=lambda r: r.get("metric_value", 0))
        stats = self._compute_stats(experiment_records, direction)
        sections = [self._title(), self._abstract(experiment_records, stats),
            self._introduction(program_config), self._methodology(experiment_records),
            self._results(experiment_records, stats, best), self._conclusion(experiment_records, stats)]
        return "\n\n---\n\n".join(sections)

    def _title(self): return f"# {self.title_prefix} Experiment Results\n\n**Date**: {datetime.now().strftime('%B %d, %Y')}\n**Generated by**: AutoResearch Framework"

    def _abstract(self, records, stats):
        n = len(records); improvement = stats.get("improvement_pct", 0)
        metric_name = records[0].get('metric_name', 'val_loss')
        return f"""## Abstract
This paper presents results from {n} automated experiments optimizing {metric_name}.
The best configuration achieved {metric_name} of {stats.get('best', 0):.6f}, representing {improvement:.2f}% improvement from baseline.
- Total experiments: {n}
- Best metric: {stats.get('best', 0):.6f}
- Average metric: {stats.get('mean', 0):.6f}"""

    def _introduction(self, program_config):
        return "## 1. Introduction\n\nAutomated machine learning research enables systematic exploration of model configurations. This paper documents autonomous optimization results."

    def _methodology(self, records):
        return f"""## 2. Methodology
The system performed {len(records)} experiments exploring architecture and hyperparameter configurations under fixed time budgets.

### Search Dimensions
- Model architecture (layers, hidden dimensions, activation functions)
- Hyperparameters (learning rate, batch size, weight decay)
- Regularization (dropout, optimizer choice)

### Method
The autoresearch framework uses a ratchet-based experiment loop where each configuration is evaluated, compared against the best known result, and retained or discarded accordingly."""

    def _results(self, records, stats, best):
        rows = ""
        for i, r in enumerate(records[:20]):
            rows += f"| {i+1} | {r.get('experiment_name','exp')} | {r.get('metric_value',0):.6f} | {r.get('status','pending')} |\n"
        return f"""## 3. Results
| ID | Name | Metric | Status |
|----|------|--------|--------|
{rows}
**Summary Statistics**:
- Best metric: {stats.get('best', 0):.6f}
- Mean metric: {stats.get('mean', 0):.6f}
- Standard deviation: {stats.get('std', 0):.6f}
- Improvement: {stats.get('improvement_pct', 0):.2f}%

**Best Configuration**: {json.dumps(best.get('params', {}), indent=2)}"""

    def _conclusion(self, records, stats):
        return f"""## 4. Conclusion
The autoresearch framework successfully optimized {len(records)} experiments, achieving {stats.get('improvement_pct', 0):.2f}% improvement over the baseline.
Key findings:
1. Automated experimentation identified optimal configurations without human intervention
2. The ratchet-based approach ensured systematic improvement tracking
3. Architecture and hyperparameter exploration proved complementary

### Future Work
- Multi-objective optimization balancing metric and training time
- Integration of larger language models for hypothesis generation
- Distributed experiment execution across multiple GPUs"""

    def _empty_paper(self): return "# AutoResearch\nNo experiment data available."

    def _compute_stats(self, records, direction="lower"):
        if not records: return {"mean": 0, "std": 0, "min": 0, "max": 0, "best": 0, "count": 0, "improvement_pct": 0}
        # Filter out non-finite metrics (failed experiments record inf)
        metrics = [r.get("metric_value", 0) for r in records if math.isfinite(r.get("metric_value", 0))]
        if not metrics: return {"mean": 0, "std": 0, "min": 0, "max": 0, "best": 0, "count": 0, "improvement_pct": 0}
        n = len(metrics); mean = sum(metrics) / n; std = statistics.stdev(metrics) if n > 1 else 0
        best_val = min(metrics) if direction == "lower" else max(metrics)
        if direction == "lower":
            improvement = (metrics[0] - best_val) / abs(metrics[0]) * 100 if metrics[0] != 0 else 0
        else:
            improvement = (best_val - metrics[0]) / abs(metrics[0]) * 100 if metrics[0] != 0 else 0
        return {"mean": mean, "std": std, "min": min(metrics), "max": max(metrics), "best": best_val, "count": n,
            "improvement_pct": improvement}

    def save(self, paper_content, output_path="papers/generated_paper.md"):
        Path(output_path).parent.mkdir(parents=True, exist_ok=True)
        with open(output_path, "w") as f: f.write(paper_content)
        return output_path